@startuml
class Edificio {
- contadorVisitas: int
- nombre: String
+ visitar(r : Reloj): Pista
}

class Ciudad {
    + visitar(edificio : String, r : Reloj): Pista
}

class Jugador {
    + visitar(edificio:String, r : Reloj): Pista
}

class Mision{
    - fechaLimite: DateTime
    + plazoExcedido(r : Reloj): bool
}

class Reloj{
    - fechaActual: DateTime
    + incrementar(horas : int): void
    + esMayor(fecha : DateTime): bool
}

class Pista {
    - contenido: String
    + mostrar(): String
}

Pista "1" <-right-  Edificio
Ciudad o-- "3" Edificio
Jugador -->"1" Ciudad: está en una
Jugador o--"1.." Mision: tiene
Edificio ..> Reloj: actualiza
Mision ..> Reloj

@enduml
