@startuml

class CasoAsignado {
    + finalizar() : void
    + finalizarSinExito() : void

    + cargarEdificios() : void
    + cargarPistasLadron() : void
}

class AlgoThief {
 + generarPartida() : void
 + finalizar(): void
 + finalizar(Objeto objetoRobado): void
}

abstract class Objeto {
    -  nombre : String
    -  nombreCiudad : String
    + {abstract} generarRecorrido() : void

}

class Ladron {
    + interactuar() : void
    + generarPista() : void

}

class Ciudad{
    - posicion :  Posicion
    - nombre :  String
    - informacion :  String


}

class DescripcionCiudad{
            - bandera : String
        - moneda  : String
        - monumento :String
        + generarPista () : void
}

class Descripcion{
    - nombre : String
    - sexo  : String
    - hobby :String
    -  cabello : String
    - seña : String
    - String  : vehiculo
    -  contador : int;
    + comparar(d : Descripcion) : boolean


}

AlgoThief "1" --upo  CasoAsignado
Objeto "1" --upo CasoAsignado
Ciudad "3...n" --upo CasoAsignado
Ladron "1"--upo CasoAsignado
Descripcion "1" --upo Ladron
DescripcionCiudad "1" --upo Ciudad

@enduml