@startuml
skinparam style strictuml

actor TestCase

participant "Jugador" as jugador
participant "Ciudad" as ciudad
participant "Banco" as banco
participant "Mision" as mision
participant "tiempo : Tiempo" as tiempo
participant "Pista" as pista

TestCase -> jugador: entrar("Banco"): String
activate jugador
jugador -> mision: visitar("Banco"): String
activate mision
mision -> ciudad: visitar("Banco", tiempo): String
activate ciudad
ciudad -> banco: visitar(tiempo): String
activate banco
banco -> tiempo: incrementar(1)
banco -> pista: emitirPista(): String
activate pista
return "Pesos Argentinos"
return "Pesos Argentinos"
return "Pesos Argentinos"
return "Pesos Argentinos"
return "Pesos Argentinos"

@enduml
