@startuml
skinparam style strictuml
title:  El Jugador visita por primera vez un Edificio
actor TestCase

participant " : Jugador" as jugador
participant " : Ciudad" as ciudad
participant " : Edificio" as banco
participant "reloj : Reloj" as reloj
participant " : Mision" as mision

TestCase -> jugador: visitar("Banco", reloj): Pista
activate jugador
jugador -> ciudad: visitar("Banco", reloj): Pista
activate ciudad
ciudad -> banco: visitar(reloj): Pista
activate banco
banco -> reloj: incrementar(1 hora):
return pista
return pista
jugador -> mision: plazoExcedido(reloj): bool
activate mision
mision -> reloj: esMayor(fechaHora): bool
activate reloj
return false
return false
return pista

@enduml
