@startuml
skinparam style strictuml
title:  El Policía entra a un edificio y sufre una herida de cuchillo por primera vez
actor TestCase

participant " policia : Policia" as policia
participant " : Ciudad" as ciudad
participant " : Edificio" as banco
participant "reloj : Reloj" as reloj
participant "arma : Cuchillo" as arma

TestCase -> policia: visitar("Banco", reloj): Interactuable
activate policia
policia -> ciudad: visitar("Banco", reloj): Interactuable
activate ciudad
ciudad -> banco: visitar(reloj): Interactuable
activate banco
banco -> reloj: incrementar(1 hora):
return arma
return arma
return arma
TestCase -> arma: interactuar(policia, reloj): void
activate arma
arma -> reloj: incrementar(2 horas): void

@enduml
