@startuml
skinparam style strictuml

actor TestCase

participant "Jugador" as jugador
participant "Ciudad" as ciudad
participant "Banco" as banco
participant "Mision" as mision
participant "Tiempo" as tiempo
participant "Pista" as pista

TestCase -> jugador: entrar("Banco"):
jugador -> ciudad: visitar("Banco"): int
activate ciudad
ciudad -> banco: visitar(): int
activate banco 
banco -> pista: emitirPista():
activate pista
return "Pesos Argentinos"
banco --> TestCase: "Pesos Argentinos" (println)
return 1
return 1
jugador -> mision: aumentarTiempo(1):
activate mision
mision -> tiempo: incrementar(1):

@enduml
