@startuml
skinparam style strictuml
title:  Un policia novato entra por primera vez a un banco en montreal y recibe una herida de cuchillo
actor TestCase

participant "policia : Policia" as policia
participant "montreal : Ciudad" as ciudad
participant "banco : Edificio" as banco
participant "reloj : Reloj" as reloj
participant "tiempoVisita : Tiempo" as tiempoVisita
participant "tiempoHerida : Tiempo" as tiempoHerida
participant "cuchillo : Cuchillo" as cuchillo
participant "tiempoTranscurrido : Tiempo" as tiempoTranscurrido

TestCase -> policia: visitar(banco, reloj): Interactuable
activate policia
policia -> ciudad: visitar(banco, reloj): Interactuable
activate ciudad
ciudad -> ciudad: buscarEdificio(banco)
ciudad -> banco: visitar(reloj): Interactuable
activate banco
banco -> tiempoVisita ** : Tiempo(1)
banco -> reloj: incrementar(tiempoVisita):
activate reloj
activate tiempoTranscurrido
reloj -> tiempoTranscurrido:incrementar()
reloj -> tiempoTranscurrido:actualizar()
reloj -> reloj:horaDeDormir()
reloj -> reloj: verificarTiempoExcedido()
banco --> ciudad:cuchillo
activate cuchillo
ciudad -->policia:cuchillo
policia -> cuchillo : interactuar(policia,reloj) : void
cuchillo -> tiempoHerida ** : Tiempo(2)
cuchillo -> reloj: incrementar(tiempoHerida)
reloj -> tiempoTranscurrido:incrementar()
reloj -> tiempoTranscurrido:actualizar()
reloj -> reloj:horaDeDormir()
reloj -> reloj: verificarTiempoExcedido()

@enduml