@startuml
skinparam style strictuml
title:  El Policía duerme

actor TestCase

participant " : Policia" as jugador
participant "reloj : Reloj" as reloj
participant "tiempoTranscurrido : Tiempo" as tiempo


TestCase -> jugador: dormir(reloj)
activate jugador
jugador -> reloj: incrementar( new Tiempo(8))
activate reloj
reloj -> tiempo: incrementar( 8 horas)

@enduml
