@startuml
skinparam style strictuml
title:  Un policia novato visita por primera vez a un banco en montreal y recibe una pista
actor TestCase

participant "policia : Policia" as policia
participant "montreal : Ciudad" as ciudad
participant "banco : Edificio" as banco
participant "reloj : Reloj" as reloj
participant "pista : Pista" as pista

TestCase -> policia: visitar(banco, reloj): Interactuable
activate policia
policia -> ciudad: visitar(banco, reloj): Interactuable
activate ciudad
ciudad -> ciudad: buscarEdificio(banco)
ciudad -> banco: visitar(reloj): Interactuable
activate banco
activate reloj
banco -> reloj: incrementar(tiempo):
banco --> ciudad:pista
ciudad -->policia:pista

policia -> pista : interactuar(policia,reloj) : void
policia --> TestCase:pista
@enduml