@startuml
skinparam style strictuml
title:  El Policía encuentra al Ladrón
actor TestCase

participant " policia : Policia" as policia
participant " : Ciudad" as ciudad
participant " : Edificio" as banco
participant "reloj : Reloj" as reloj
participant " ladron : Ladron" as ladron

TestCase -> policia: visitar("Banco", reloj): Interactuable
activate policia
policia -> ciudad: visitar("Banco", reloj): Interactuable
activate ciudad
ciudad -> banco: visitar(reloj): Interactuable
activate banco
banco -> reloj: incrementar(1 hora):
return ladron
return ladron
return ladron
TestCase -> ladron: interactuar(policia, reloj): void
activate ladron
ladron -> policia: terminarMision(): void
deactivate ladron

@enduml