@startuml
skinparam style strictuml
title:  Caso en el que el edificio contiene un ladrón y el policía tiene un orden de arresto emitido con caso asignado

participant "policia : Policia" as policia
participant "ladron : Ladron" as ladron
participant "orden : OrdenEmitida" as ordenArresto
participant "caso : CasoAsignado" as caso
participant "juego : AlgoThief" as juego

policia -> ladron : interactuar(policia,reloj) : void
activate ladron
ladron -> policia : arrestar() : void
policia -> ordenArresto : arrestar(policia)
activate ordenArresto
ordenArresto -> policia: sumarArresto(1)
policia -> caso:finalizar()
caso -> juego:finalizar(caso)

@enduml