@startuml
skinparam style strictuml

title: Policía viaja de Montreal a México

actor TestCase

participant " : Jugador" as jugador
participant " rango : Novato" as rango
participant " montreal : Ciudad" as montreal
participant " mexico : Ciudad" as mexico
participant " posMontreal : Posicion" as posicionMontreal
participant " posMexico : Posicion" as posicionMexico
participant "reloj : Reloj" as reloj

TestCase -> jugador: viajar(mexico, reloj): void
jugador -> rango: viajar(montreal, mexico, reloj): void
rango -> mexico: tiempoViaje(montreal, 900): double
activate mexico
mexico -> mexico: calcularDistanciaCon(montreal): double
activate mexico
mexico -> montreal: calcularDistancia(posMexico): double
activate montreal
montreal -> posicionMontreal: calcularDistanciaCon(posMexico): double
activate posicionMontreal
posicionMontreal -> posicionMexico: calcularDistancia(45.51, -73.59): double
activate posicionMexico
return 3728.32 km
return 3728.32 km
return 3728.32 km
deactivate mexico
return 3728.32 km / 900 km/hora = 4 horas
rango -> reloj: incrementar(new Tiempo(4 horas): void


@enduml