@startuml
skinparam style strictuml

title: Policía viaja de Montreal a México

actor TestCase

participant "policia : Policia" as policia
participant " rango : Novato" as rango
participant " montreal : Ciudad" as montreal
participant " mexico : Ciudad" as mexico
participant " posMontreal : Posicion" as posicionMontreal
participant " posMexico : Posicion" as posicionMexico
participant "reloj : Reloj" as reloj
participant "tiempo : Tiempo" as tiempo

TestCase -> policia: viajar(mexico, reloj): void
policia -> rango: viajar(montreal, mexico, reloj): void

rango -> mexico: tiempoViaje(montreal,900): double
activate mexico
mexico -> mexico: calcularDistanciaCon(montreal)/900: double
mexico -> montreal: calcularDistancia(posMexico): double
activate montreal
montreal -> posicionMontreal: calcularDistanciaCon(posMexico): double
activate posicionMontreal
posicionMontreal -> posicionMexico: calcularDistancia(45.51, -73.59): double
activate posicionMexico
return 3728.32 km
return 3728.32 km
return 3728.32 km
return 3728.32 km / 900 km/hora = 4 horas
rango -> tiempo ** :Tiempo(4)
activate reloj
rango -> reloj: incrementar(tiempo): void
@enduml