@startuml
skinparam style strictuml
title: Caso en el que el edificio contiene un ladrón y el policía tiene un orden de arresto no emitido

participant "policia : Policia" as policia
participant "ladron : Ladron" as ladron
participant "orden : OrdenNoEmitida" as ordenArresto

policia -> ladron : interactuar(policia,reloj) : void
activate ladron
ladron -> policia : arrestar() : void
policia -> ordenArresto : arrestar(policia)
activate ordenArresto
ordenArresto -> OrdenNoEmitidaError ** : OrdenNoEmitidaError()
@enduml