@startuml
skinparam style strictuml
title:  Un policía entra por primera vez a un banco en montreal y encuentra al ladrón sin una orden de arresto emitida
actor TestCase

participant "policia : Policia" as policia
participant "montreal : Ciudad" as ciudad
participant "banco : Edificio" as banco
participant "reloj : Reloj" as reloj
participant "tiempo : Tiempo" as tiempo
participant "ladron : Ladron" as ladron
participant "orden : OrdenNoEmitida" as ordenArresto
participant "tiempoTranscurrido : Tiempo" as tiempoTranscurrido

TestCase -> policia: visitar(banco, reloj): Interactuable
activate policia
policia -> ciudad: visitar(banco, reloj): Interactuable
activate ciudad
ciudad -> ciudad: buscarEdificio(banco)
ciudad -> banco: visitar(reloj): Interactuable
activate banco
banco -> tiempo ** : Tiempo(1)
banco -> reloj: incrementar(tiempo):
activate reloj
activate tiempoTranscurrido
reloj -> tiempoTranscurrido:incrementar()
reloj -> tiempoTranscurrido:actualizar()
reloj -> reloj:horaDeDormir()
reloj -> reloj: verificarTiempoExcedido()
policia -> ladron : interactuar(policia,reloj) : void
activate ladron
ladron -> policia : arrestar() : void
policia -> ordenArresto : arrestar(policia)
activate ordenArresto
ordenArresto -> OrdenNoEmitidaError ** : OrdenNoEmitidaError()
@enduml